---
- hosts: all
  tasks:
  - name: Pull down logs to executor
    ignore_errors: True
    synchronize:
      src: "{{ zuul.project.src_dir }}/config.log"
      dest: "{{ zuul.executor.log_root }}/config.log"
      mode: pull
      extra_opts:
        - --no-same-owner
...
